language: python
python:
    - "2.7"
    - "3.5"


env: 
    - VERSION=$TRAVIS_BUILD_NUMBER

sudo: required

services:
  - docker

install: ./go setup

script: 
    - ./go test
    - ./go build
    - ./go push
    - ./go deploy
