language: python
python:
    - "2.7"
    - "3.5"


env: 
    - VERSION=$TRAVIS_BUILD_NUMBER
    - secure: "KRx4TkwFRMFde2GZ3NNqT5Bm8hgWjg4LoJoO4H/f9Xq39JjW9145DuLfNslp8rHHMUwyMADWX4ImZLrDPBQKpMuWBPqKtAGrtG2X57LzY1oiOD6PGfO6O38zOPDeLdjOSeWd0kQ4RlmSXwHY91tt2jRKEJ9Qz8zQ6r1MyE+s/dPzfAfezj1RpJ5OFVgEr2K0R1W9/DE9ySmTp/PYD7NpMvbwk/hGUoZfjvkIOG5zb7H/U+8pBlQMAeBLu7aaaVhnXEOZa8+/gUPidthc9JbbqLhFvkk0rfwj9a+HVrjLqXs7Tf0eWGTYnQvvMo4PVNezc+6xcaiVRKguSjglFE12jjXxgIp+O6xKZyeG/an6VyCPkJ5Ut7CLWp/CiwxDFOqe9cdcFAa74Bn3zYSCcWi2XjafRUVHv9gYUm0AEajuJYFw5xC833zDTSCXTk4uIPsPaFlDUEYwikmLCKaydp7j17w48vYhHt0/FpnLTp0Zds3HDsKtgm+NHe+fb46HH8EDDFUDDaeILnHiYmJ7Flj78gEBEdWQgtEc0avw5hDothOeOE7BVTU0tH2/IufW5u+jezNg+vhTJsceIUuMQ5A0pkb7c2WLbB5noa/NU83dx1MfOU/YRZpuLN2tnxZPICMAtEBED8gFZo8sRve7N7Gr5BJe/qJyKPk2DFCbyasST6M="

sudo: required

services:
  - docker

install: ./go setup

script: 
    - ./go test
    - ./go build

deploy: 
    provider: script
    script: 
        - ./go push
        - ./go deploy staging

