resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/hamvocke/continuous-delivery.git
    branch: master

jobs:
- name: unit-test
  plan:
  - get: git-repo
    trigger: true
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
      inputs:
      - name: git-repo
      run:
        dir: git-repo/
        path: ci/test
